site_name: Docs | Bagne Tyron-Jean
site_url: https://tyron-docs.readthedocs.io/
use_directory_urls: false
docs_dir: 'docs'
repo_url: 'https://github.com/1Tyron140/doc'

theme:
  name: material
  highlightjs: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.superfences
  

nav:
    - Home: 'index.md'
    - SIO:
        - Nextcloud: 
            Introduction: 'sio/nextcloud/introduction.md'
            Installation: 'sio/nextcloud/installation.md'
            Confiuration: 'sio/nextcloud/configuration.md'
        - pFsense: 'sio/pfsense/index.md'
        - GLPI: 'sio/glpi/index.md'
