site_name: Docs | Bagne Tyron-Jean
#site_url: 
use_directory_urls: false
docs_dir: 'docs'
repo_url: 'https://github.com/1Tyron140/doc'

theme:
  name: material
  highlightjs: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.superfences
  

nav:
    - Accueil: 'index.md'
    - SIO:
        - Objectif: 'sio/index.md'
        - Nextcloud: 
            - Installation d'un serveur de cloud interne Nextcloud: 'sio/nextcloud/introduction.md'
            - Installation de Nextcoud: 'sio/nextcloud/installation.md'
            - Configuration de Nextcloud: 'sio/nextcloud/configuration.md'
            - La Sécurité sur Nextcloud: 'sio/nextcloud/securite.md'
        - pFsense: 
            - Pare-feu pFsense virtuel sur ESXI: 'sio/pfsense/index.md'
            - Installation de pFsense sur ESXI: 'sio/pfsense/installation.md' 
        - GLPI: 
            - Introduction: 'sio/glpi/index.md'
        - Cacti: 
            - Introduction: 'sio/cacti/index.md'   
        - Samba: 
            - Introduction: 'sio/samba/index.md'
        - Nagios: 
            - Introduction: 'sio/nagios/index.md'
        - NAS: 
            - Introduction: 'sio/synology/index.md'
        - FTP:
            - openSUSE:
                - Introduction: 'sio/ftp/openSUSE/introduction.md'
                - Installer un FTP sur openSUSE: 'sio/ftp/openSUSE/installation.md'
                - Configuration: 'sio/ftp/openSUSE/configuration.md'
                - Sécurité: 'sio/ftp/openSUSE/securite.md'
        - SFTP:
            - openSUSE:
                - Introduction: 'sio/sftp/openSUSE/introduction.md'
                - Installer un SFTP sur openSUSE: 'sio/sftp/openSUSE/installation.md'
                - Configuration: 'sio/sftp/openSUSE/configuration.md'
                - Sécurité: 'sio/sftp/openSUSE/securite.md'
                - Guide de l'utilisateur: 'sio/sftp/openSUSE/guide_utilisateur.md'
        - Zootickoon:
            - Création du site web d'un zoo avec un CMS: 'sio/zootickoon/introduction.md'
            - Installation de XAMPP et Wordpress: 'sio/zootickoon/installation.md'
            - Configuration de la base de donnée et de wordpress: 'sio/zootickoon/configuration.md'
            - Conception du site web: 'sio/zootickoon/conception.md'
