site_name: Docs | Bagne Tyron-Jean
#site_url: 
use_directory_urls: false
docs_dir: 'docs'
repo_url: 'https://github.com/1Tyron140/doc'

theme:
  name: material
  highlightjs: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.superfences
  

nav:
    - Accueil: 'index.md'
    - SIO:
        - Objectif: 'sio/index.md'
        - Nextcloud: 
            - Installation d'un serveur de cloud interne Nextcloud: 'sio/nextcloud/introduction.md'
            - Installation de Nextcoud: 'sio/nextcloud/installation.md'
            - Configuration de Nextcloud: 'sio/nextcloud/configuration.md'
            - La Sécurité sur Nextcloud: 'sio/nextcloud/securite.md'
        - pFsense: 
            - Pare-feu pFsense virtuel sur ESXI: 'sio/pfsense/index.md'
            - Installation de pFsense sur ESXI: 'sio/pfsense/installation.md' 
        - GLPI: 
            - Gérer le parc informatique avec GLPI: 'sio/glpi/index.md'
            - Inventorier le parc Informatique avec FusionInventory: 'sio/glpi/fusion.md'
        - Cacti: 
            - Superviser une machine Windows avec Cacti: 'sio/cacti/ajouter_machine.md'   
            - Modifier MariaDB: 'sio/cacti/modifier_mariadb.md'  
        - Samba: 
            - Installation de Samba sur un serveur linux: 'sio/samba/installation_samba.md'
        - Nagios: 
            - Installer Nagios sur Debian: 'sio/nagios/installation_nagios.md'
            - Superviser une machine Linux sur Nagios: 'sio/nagios/nagios_ajouter-machine-linux.md'
            - Superviser une machine Windows sur Nagios: 'sio/nagios/nagios_superviser_windows.md'
            - Monitorer un service particulier sur Nagios: 'sio/nagios/monitorer_services.md'
            - Problème "host down" sur Nagios: 'sio/nagios/nagios_host-down.md'
        - NAS: 
            - Introduction: 'sio/synology/index.md'

        - FTP:
            - openSUSE:
                - Mise en place d'un serveur FTP sur openSUSE: 'sio/ftp/openSUSE/introduction.md'
                - Installer un FTP sur openSUSE: 'sio/ftp/openSUSE/installation.md'
                - Configuration du SFTP sur openSUSE: 'sio/ftp/openSUSE/configuration.md'
                - Quelques mesures de sécurité: 'sio/ftp/openSUSE/securite.md'
        - SFTP:
            - openSUSE:
                - Mise en place d'un SFTP sur openSUSE: 'sio/sftp/openSUSE/introduction.md'
                - Installer un SFTP sur openSUSE: 'sio/sftp/openSUSE/installation.md'
                - Configuration du SFTP sur openSUSE: 'sio/sftp/openSUSE/configuration.md'
                - Sécurité du SFTP: 'sio/sftp/openSUSE/securite.md'
                - Guide de l'utilisateur du SFTP: 'sio/sftp/openSUSE/guide_utilisateur.md'
            - debian:
                - Mise en place d'un SFTP sur Debian: 'sio\sftp\debian\introduction.md'
                - Installation du SFTP sur Debian: 'sio\sftp\debian\installation.md'
                - Configuration du SFTP sur Debian: 'sio\sftp\debian\configuration.md'
        - Zootickoon:
            - Création du site web d'un zoo avec un CMS: 'sio/zootickoon/introduction.md'
            - Installation de XAMPP et Wordpress: 'sio/zootickoon/installation.md'
            - Configuration de la base de donnée et de wordpress: 'sio/zootickoon/configuration.md'
            - Conception du site web: 'sio/zootickoon/conception.md'
            - Améliorations du référencement (SEO): 'sio/zootickoon/seo.md'
